<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net8.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<AssemblyName>Ujeby.$(MSBuildProjectName)</AssemblyName>
		<RootNamespace>Ujeby.$(MSBuildProjectName.Replace(" ", "_"))</RootNamespace>
		<Platforms>AnyCPU;x64</Platforms>
		<Configurations>Debug;Release;Debug-offline</Configurations>
		<!--<Nullable>enable</Nullable>-->
	</PropertyGroup>

	<ItemGroup>
		<!--<PackageReference Include="Ujeby.Core" Version="8.*" />-->
	</ItemGroup>

	<ItemGroup>
		<Reference Include="Ujeby.Core">
			<HintPath>..\..\Ujeby\publish\Ujeby.Core.dll</HintPath>
		</Reference>
	</ItemGroup>

</Project>
